export {
  Client,
  VAPI2_BASE_URL,
  type AttemptSSHRequest,
  type BgpDashboardOptions,
  type BindBgpGroupFirewallSetRequest,
  type BindCloudFirewallSetRequest,
  type BuildMetalRequest,
  type BuildServerRequest,
  type BuyBgpPrefixesRequest,
  type CancelCloudPackageRequest,
  type CreateAccessControlSubnetRequest,
  type CreateBgpGroupRequest,
  type CreateBgpSessionsRequest,
  type CreateDnsRecordRequest,
  type CreateDnsZoneRequest,
  type CreateFirewallRuleRequest,
  type CreateImageRequest,
  type CreateMetalRequest,
  type CreateServerRequest,
  type CreateSshKeyRequest,
  type CreateTagRequest,
  type CreateTicketRequest,
  type DdosDashboardOptions,
  type DedicatedDeviceFilterOptions,
  type DedicatedIpv4ReverseRequest,
  type DedicatedServerActionRequest,
  type DedicatedServerBuildRequest,
  type DeleteServerOptions,
  type DeploySizesQuery,
  type FirewallAvailableVmOptions,
  type FirewallRelatedSetOptions,
  type GetTicketAttachmentOptions,
  type GraphQuery,
  type PlatformLookingGlassExecuteOptions,
  type ReorderFirewallRulesRequest,
  type ReplyTicketRequest,
  type ResetServerRootPasswordRequest,
  type ScaleServerRequest,
  type ScalingOptionsQuery,
  type ServerActionOptions,
  type ServerBuild,
  type ServerNicAttachRequest,
  type ServerNicUpdateRequest,
  type StartServerRescueRequest,
  type UpdateAccessControlSubnetRequest,
  type UpdateDnsRecordRequest,
  type UpdateServerOptionsRequest,
  type UpdateSshKeyRequest,
  type UpdateTagRequest,
  type WaitForImageQueueOptions
} from "./client.js";
export {
  V3Client,
  VAPI3_BASE_URL,
  type ApplyVpcChangesOptions,
  type CloudFloatingIpv4VmRef,
  type CreateCloudFloatingIpv4Request,
  type CreateMagicMeshRequest,
  type CreateNkeClusterAddonRequest,
  type CreateNkeClusterRequest,
  type CreateOidcClientKeyRequest,
  type CreateOidcClientRequest,
  type CreateHttpLbGroupRequest,
  type CreateNlbGroupRequest,
  type CreateRouterVrfInterfaceWireguardPeerRequest,
  type CreateSslCertificateRequest,
  type CreateStorageBlockNamespaceRequest,
  type CreateStorageBlockVolumeRequest,
  type CreateStorageBucketRequest,
  type CreateStorageObjectStoreRequest,
  type CreateVpcBackendRequest,
  type CreateVpcBackendTemplateRequest,
  type CreateVpcDnatRuleRequest,
  type CreateVpcFirewallRuleRequest,
  type CreateVpcFloatingIpOptions,
  type CreateVpcFloatingIpRequest,
  type CreateVpcRequest,
  type CreateVpcSnatRuleRequest,
  type CreateRouterRequest,
  type CreateRouterVrfRequest,
  type GetRouterRoutingViewsRequest,
  type GrantCloudFloatingIpv4VmsRequest,
  type HttpLbGroupInput,
  type MagicMeshRouterInput,
  type NkeBilling,
  type NkeDnsAddonWriteConfig,
  type NkeStorageAddonWriteConfig,
  type NlbGroupInput,
  type RevokeCloudFloatingIpv4VmsRequest,
  type ReplaceHttpLbGroupRequest,
  type ReplaceNlbGroupRequest,
  type ReplaceVpcBackendsRequest,
  type ReplaceVpcBackendTemplateRequest,
  type ReplaceVpcNameserversRequest,
  type ReplaceVpcNameserversResponse,
  type RouterPrefixListInput,
  type RouterRoutingViewSelector,
  type RouterStaticRouteInput,
  type RouterVrfBgpNeighborInput,
  type RouterVrfDnatRuleInput,
  type RouterVrfInterfaceInput,
  type RouterVrfIpSecPeerInput,
  type RouterVrfSnatRuleInput,
  type RouterVrfTunnelInput,
  type UpdateMagicMeshRequest,
  type UpdateNkeClusterAddonRequest,
  type UpdateNkeClusterRequest,
  type UpdateNkeWorkerNodeRequest,
  type UpdateOidcClientKeyRequest,
  type UpdateOidcClientRequest,
  type UpdateRouterIpSecConfigRequest,
  type UpdateRouterNtpConfigRequest,
  type UpdateRouterRequest,
  type UpdateRouterVrfBgpRequest,
  type UpdateRouterVrfDhcpRequest,
  type UpdateRouterVrfRequest,
  type UpdateSslCertificateRequest,
  type UpdateStorageBlockNamespaceRequest,
  type UpdateStorageBlockVolumeRequest,
  type UpdateStorageBucketRequest,
  type UpdateStorageObjectStoreRequest,
  type UpdateVpcBackendRequest,
  type UpdateVpcBackendTemplateRequest,
  type UpdateVpcDnatRuleRequest,
  type UpdateVpcFirewallRuleRequest,
  type UpdateVpcFloatingIpRequest,
  type UpdateVpcRequest,
  type UpdateVpcSnatRuleRequest,
  type UpdateVpcSshSettingsRequest,
  type VpcBackendInput,
  type VpcDnatRulePriority,
  type VpcSnatRulePriority,
  type WaitForNkeReadyOptions,
  type WaitForRouterReadyOptions,
  type WaitForStorageReadyOptions,
  type WaitForVpcReadyOptions
} from "./v3-client.js";
export {
  decodeAccessControlSubnet,
  decodeAccountAgreement,
  decodeAccountLimit,
  decodeBgpAsn,
  decodeBgpGroup,
  decodeBgpGroupFirewallSetBinding,
  decodeBgpPrefix,
  decodeBgpSession,
  decodeBillingPackage,
  decodeBootProfile,
  decodeCloudCapacity,
  decodeCloudFloatingIpv4,
  decodeCloudFloatingIpv4Vm,
  decodeCloudLocation,
  decodeCloudNetworkingLocation,
  decodeCloudPackage,
  decodeCloudPool,
  decodeColocationPackage,
  decodeColocationService,
  decodeContractUsage,
  decodeCreateImageResponse,
  decodeCreateSslCertificateResponse,
  decodeDatacenter,
  decodeDdosAttack,
  decodeDdosDashboard,
  decodeDdosRule,
  decodeDedicatedCapacity,
  decodeDedicatedDiskLayout,
  decodeDedicatedLocation,
  decodeDedicatedOsProfile,
  decodeDedicatedRescueOsProfile,
  decodeDedicatedServerBuildStatus,
  decodeDeleteImageResponse,
  decodeDeleteServerResponse,
  decodeDnsRecord,
  decodeDnsZone,
  decodeFirewallExternalIpSet,
  decodeFirewallManageEnabled,
  decodeFirewallMatchCriteria,
  decodeFirewallRule,
  decodeFirewallSet,
  decodeFirewallSetVm,
  decodeFloatingIpLocation,
  decodeGraph,
  decodeHttpLbGroup,
  decodeImage,
  decodeImageQueueStatus,
  decodeIpTransitIpAddress,
  decodeIpTransitPort,
  decodeIpTransitService,
  decodeJobStatus,
  decodeKernel,
  decodeLocation,
  decodeLocationByCurrentIp,
  decodeLocationSummary,
  decodeMagicMesh,
  decodeMeshRouter,
  decodeMetal,
  decodeMetalBuild,
  decodeMetricNames,
  decodeNetworkIps,
  decodeNkeAccessUrls,
  decodeNkeAddon,
  decodeNkeAddonCatalogEntry,
  decodeNkeCluster,
  decodeNkeClusterDnsZone,
  decodeNkeLogEntry,
  decodeNkeWorkerNode,
  decodeNlbGroup,
  decodeOidcClient,
  decodeOidcClientAuthLog,
  decodeOidcClientBareMetalServer,
  decodeOidcClientChangeLog,
  decodeOidcClientDetail,
  decodeOidcClientKey,
  decodeOidcClientVm,
  decodeOs,
  decodePackage,
  decodeRouter,
  decodeRouterConfig,
  decodeRouterIpSecConfig,
  decodeRouterNtpConfig,
  decodeRouterPrefixList,
  decodeRouterStaticRoute,
  decodeRouterVrfBgpConfig,
  decodeRouterVrfBgpNeighbor,
  decodeRouterVrfConfig,
  decodeRouterVrfDhcpConfig,
  decodeRouterVrfDnatRule,
  decodeRouterVrfInterface,
  decodeRouterVrfInterfaceMap,
  decodeRouterVrfInterfaceWireguardPeer,
  decodeRouterVrfIpSecPeer,
  decodeRouterVrfMap,
  decodeRouterVrfSnatRule,
  decodeRouterVrfTunnel,
  decodeUpdateRouterVrfBgpResult,
  decodePlatformChangeLogEntry,
  decodePlatformEvents,
  decodePlatformLookingGlassInit,
  decodePlatformLookingGlassResult,
  decodePlatformMaintenanceInfo,
  decodePlatformStatus,
  decodeSecretList,
  decodeSecretListValue,
  decodeServer,
  decodeServerBuildStatus,
  decodeServerIPAddress,
  decodeServerNic,
  decodeServerNicFromResponse,
  decodeServerStatus,
  decodeService,
  decodeSize,
  decodeSshKey,
  decodeSslCertificate,
  decodeStatisticResult,
  decodeStorageBlockNamespace,
  decodeStorageBlockVolume,
  decodeStorageBucket,
  decodeStorageHardwareClass,
  decodeStorageLocation,
  decodeStorageObjectStore,
  decodeStorageType,
  decodeStorageTypes,
  decodeTag,
  decodeTagLog,
  decodeTagResource,
  decodeTicket,
  decodeTicketAttachment,
  decodeTicketDepartment,
  decodeTicketReply,
  decodeTransitPackage,
  decodeTransportPort,
  decodeTransportService,
  decodeVlan,
  decodeVlanProvisionedLocation,
  decodeVpc,
  decodeVpcBackend,
  decodeVpcBackendTemplate,
  decodeVpcDnatRule,
  decodeVpcFirewallRule,
  decodeVpcFloatingIp,
  decodeVpcIpReservations,
  decodeVpcNameserverList,
  decodeVpcNameservers,
  decodeVpcPortRange,
  decodeVpcSnatRule,
  decodeVpcSshKey,
  decodeVpcSshSettings,
  type AccessControlSubnet,
  type AccountAgreement,
  type AccountLimit,
  type BgpAsn,
  type BgpDashboard,
  type BgpGroup,
  type BgpGroupFirewallSetBinding,
  type BgpPrefix,
  type BgpSession,
  type BgpSessionPrefix,
  type BgpSummary,
  type BillingPackage,
  type BootProfile,
  type CloudCapacity,
  type CloudFloatingIpv4,
  type CloudFloatingIpv4Vm,
  type CloudLocation,
  type CloudNetworkingLocation,
  type CloudPackage,
  type CloudPool,
  type ColocationPackage,
  type ColocationService,
  type ContractUsage,
  type CreateImageResponse,
  type CreateSslCertificateResponse,
  type Datacenter,
  type DdosAttack,
  type DdosDashboard,
  type DdosRule,
  type DdosRuleAction,
  type DdosRulePrefix,
  type DedicatedCapacity,
  type DedicatedDevice,
  type DedicatedDiskLayout,
  type DedicatedIdName,
  type DedicatedLocation,
  type DedicatedOsProfile,
  type DedicatedPlan,
  type DedicatedPowerStatus,
  type DedicatedRescueOsProfile,
  type DedicatedServerBuildStatus,
  type DeleteImageResponse,
  type DeleteServerResponse,
  type DnsRecord,
  type DnsZone,
  type FirewallExternalIpSet,
  type FirewallManageEnabled,
  type FirewallMatchCriteria,
  type FirewallMatchOptions,
  type FirewallRule,
  type FirewallSet,
  type FirewallSetVm,
  type FloatingIpLocation,
  type Graph,
  type HttpLbGroup,
  type HttpLbGroupBackend,
  type HttpLbGroupHealthCheck,
  type HttpLbGroupHealthCheckActive,
  type HttpLbGroupHealthCheckPassive,
  type HttpLbGroupMatch,
  type HttpLbGroupRule,
  type HttpLbGroupRuleMatch,
  type HttpLbGroupRuleSsl,
  type Image,
  type ImageBuild,
  type ImageQueueStatus,
  type IpTransitIpAddress,
  type IpTransitPort,
  type IpTransitService,
  type JobStatus,
  type JsonObject,
  type Kernel,
  type LocationByCurrentIp,
  type LocationSummary,
  type MagicMesh,
  type MeshRouter,
  type Metal,
  type MetalBuild,
  type MetricName,
  type MetricNames,
  type MetricSummary,
  type MetricTimeWindow,
  type NetworkIp,
  type NetworkIps,
  type NkeAccessUrls,
  type NkeAddon,
  type NkeAddonCatalogEntry,
  type NkeAddonConfig,
  type NkeCluster,
  type NkeClusterDnsZone,
  type NkeDnsAddonZone,
  type NkeLogEntry,
  type NkeStorageAddonIntegration,
  type NkeWorkerNode,
  type NlbGroup,
  type NlbGroupBackend,
  type NlbGroupHealthCheck,
  type NlbGroupMatch,
  type NlbGroupRule,
  type NlbGroupRulePorts,
  type NonCloudPackageDetails,
  type OidcClient,
  type OidcClientAuthLog,
  type OidcClientBareMetalServer,
  type OidcClientChangeLog,
  type OidcClientDetail,
  type OidcClientKey,
  type OidcClientVm,
  type Os,
  type PlatformChangeLogEntry,
  type PlatformEvent,
  type PlatformEvents,
  type PlatformLookingGlassInit,
  type PlatformLookingGlassResult,
  type PlatformMaintenanceInfo,
  type PlatformStatusLocation,
  type PlatformStatusService,
  type Router,
  type RouterBuildEvent,
  type RouterConfig,
  type RouterConfigMetadata,
  type RouterDhcpRange,
  type RouterDhcpServer,
  type RouterDhcpStaticRoute,
  type RouterIpSecConfig,
  type RouterIpSecEspGroup,
  type RouterIpSecIkeGroup,
  type RouterLocation,
  type RouterNtpConfig,
  type RouterNtpUpstream,
  type RouterPrefixList,
  type RouterPrefixListRule,
  type RouterStaticRoute,
  type RouterStaticRouteVia,
  type RouterVrfBgpConfig,
  type RouterVrfBgpNeighbor,
  type RouterVrfBgpNeighborAsn,
  type RouterVrfBgpNeighborEnabledIpVersion,
  type RouterVrfBgpNeighborSource,
  type RouterVrfBgpNetwork,
  type RouterVrfBgpRouteMap,
  type RouterVrfBgpRouteMapRule,
  type RouterVrfConfig,
  type RouterVrfDhcpConfig,
  type RouterVrfDnatRule,
  type RouterVrfDnatRulePriority,
  type RouterVrfInterface,
  type RouterVrfInterfaceWireguardPeer,
  type RouterVrfIpSecConfig,
  type RouterVrfIpSecOverlayNetwork,
  type RouterVrfIpSecPeer,
  type RouterVrfNatMatch,
  type RouterVrfNatTranslation,
  type RouterVrfRoutesConfig,
  type RouterVrfServices,
  type RouterVrfSnatRule,
  type RouterVrfSnatRulePriority,
  type RouterVrfTunnel,
  type RouterVrfTunnelEndpoint,
  type SecretList,
  type SecretListValue,
  type Server,
  type ServerBuildStatus,
  type ServerIPAddress,
  type ServerNic,
  type ServerStatus,
  type Service,
  type Size,
  type SshKey,
  type SslCertificate,
  type SslCertificateDates,
  type StatisticResult,
  type StatisticSample,
  type StorageBlockNamespace,
  type StorageBlockNamespaceMetadata,
  type StorageBlockVolume,
  type StorageBlockVolumeMetadata,
  type StorageBucket,
  type StorageBucketMetadata,
  type StorageCapacity,
  type StorageHardwareClass,
  type StorageLocation,
  type StorageObjectStore,
  type StorageObjectStoreMetadata,
  type StorageType,
  type Tag,
  type TagLog,
  type TagResource,
  type Ticket,
  type TicketAttachment,
  type TicketDepartment,
  type TicketListOptions,
  type TicketReply,
  type TransitPackage,
  type TransportPort,
  type TransportService,
  type UpdateRouterVrfBgpResult,
  type V3Location,
  type V3Package,
  type Vlan,
  type VlanProvisionedLocation,
  type Vpc,
  type VpcBackend,
  type VpcBackendTemplate,
  type VpcDnatMatch,
  type VpcDnatRule,
  type VpcDnatTranslation,
  type VpcFirewallRule,
  type VpcFloatingIp,
  type VpcIpReservations,
  type VpcMetadata,
  type VpcNameserver,
  type VpcNameservers,
  type VpcPortRange,
  type VpcSnatAddressRange,
  type VpcSnatMatch,
  type VpcSnatRule,
  type VpcSnatTranslation,
  type VpcSshBastion,
  type VpcSshKey,
  type VpcSshSettings,
  type WireguardPeerAllowedIp
} from "./decoders.js";
export {
  NetActuateContractError,
  NetActuateError,
  NetActuateNotFoundError,
  formatApiError,
  isContractError,
  isNotFoundError,
  redactUrl,
  type ApiErrorContext,
  type HttpMethod
} from "./errors.js";
export { type ClientOptions, type Transport, type TransportResponse } from "./transport.js";
export { parseV3ListPage, type V3ListMeta, type V3ListPage } from "./vapi3-list.js";
